import type { Post, InterestCategory } from "./types";
import { detectPostInterests } from "./useEngagementStore";

// Fonction pour créer un post complet avec tous les champs
function createPost(
  base: Omit<Post, "shares" | "views" | "viralityScore" | "engagementRate" | "peakViewsPerMinute" | "viewsHistory" | "detectedInterests">
): Post {
  const views = Math.floor(Math.random() * 5000) + 100;
  const engagementRate = views > 0 
    ? ((base.likes + base.comments.length * 2) / views) * 100 
    : 0;
  
  return {
    ...base,
    shares: Math.floor(base.likes * 0.1),
    views,
    viralityScore: Math.min(100, Math.floor(base.likes / 5) + Math.floor(engagementRate * 2)),
    engagementRate,
    peakViewsPerMinute: Math.floor(Math.random() * 50) + 1,
    viewsHistory: [],
    detectedInterests: detectPostInterests(base.text),
  };
}

export const mockPosts: Post[] = [
  createPost({
    id: "p001",
    authorId: "user_camille",
    author: "Camille",
    handle: "camille",
    text: "Magnifique coucher de soleil sur le lac Léman ce soir ! 🌅 Les couleurs sont incroyables. #Lausanne #Suisse",
    createdAtISO: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    kind: "normal",
    category: "vibe",
    signal: "strong",
    geoMode: "precise",
    status: "active",
    likes: 156,
    likedBy: ["noah", "emma", "admin"],
    comments: [
      {
        id: "c001",
        authorId: "user_noah",
        author: "Noah",
        handle: "noah",
        text: "Superbe photo ! 📸",
        createdAtISO: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        likes: 12,
      },
    ],
    media: {
      type: "image",
      url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    },
    lon: 6.6323,
    lat: 46.5197,
    tags: ["nature", "photography", "travel"],
  }),
  createPost({
    id: "p002",
    authorId: "user_noah",
    author: "Noah",
    handle: "noah",
    text: "🚨 ALERTE TRAFIC : Accident sur le périphérique nord de Paris, bouchons importants. Évitez la zone si possible !",
    createdAtISO: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    kind: "normal",
    category: "alert",
    signal: "strong",
    geoMode: "precise",
    status: "active",
    likes: 234,
    likedBy: ["camille", "emma"],
    comments: [
      {
        id: "c002",
        authorId: "user_emma",
        author: "Emma",
        handle: "emma",
        text: "Merci pour l'info ! 🙏",
        createdAtISO: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
        likes: 5,
      },
      {
        id: "c003",
        authorId: "user_camille",
        author: "Camille",
        handle: "camille",
        text: "C'est encore bloqué ?",
        createdAtISO: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        likes: 2,
      },
    ],
    lon: 2.3522,
    lat: 48.8866,
  }),
  createPost({
    id: "p003",
    authorId: "user_emma",
    author: "Emma",
    handle: "emma",
    text: "Concert incroyable de Coldplay à Wembley ce soir ! 🎸🎤 L'ambiance est électrique ! #Coldplay #London #music",
    createdAtISO: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    kind: "normal",
    category: "event",
    signal: "strong",
    geoMode: "precise",
    status: "active",
    likes: 423,
    likedBy: ["camille", "noah", "admin"],
    comments: [],
    media: {
      type: "youtube",
      url: "https://www.youtube.com/watch?v=dvgZkm1xWPE",
    },
    lon: -0.2795,
    lat: 51.5560,
    tags: ["music", "concert", "events"],
  }),
  createPost({
    id: "p004",
    authorId: "admin_001",
    author: "Admin GlobeHub",
    handle: "admin",
    text: "📢 Nouvelle fonctionnalité tech : Vous pouvez maintenant ajouter des vidéos YouTube à vos posts ! Essayez dès maintenant. #innovation",
    createdAtISO: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    kind: "promoted",
    category: "news",
    signal: "none",
    geoMode: "none",
    status: "active",
    likes: 89,
    likedBy: ["camille", "noah", "emma"],
    comments: [],
  }),
  createPost({
    id: "p005",
    authorId: "user_camille",
    author: "Camille",
    handle: "camille",
    text: "Randonnée au Mont Blanc terminée ! 🏔️ Vue à couper le souffle au sommet. 6 heures d'effort fitness mais ça valait le coup ! #nature #travel",
    createdAtISO: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    kind: "normal",
    category: "vibe",
    signal: "weak",
    geoMode: "approximate",
    status: "active",
    likes: 312,
    likedBy: ["noah", "emma"],
    comments: [
      {
        id: "c004",
        authorId: "user_noah",
        author: "Noah",
        handle: "noah",
        text: "Bravo ! C'est sur ma bucket list 🎯",
        createdAtISO: new Date(Date.now() - 47 * 60 * 60 * 1000).toISOString(),
        likes: 8,
      },
    ],
    media: {
      type: "image",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    },
    lon: 6.8652,
    lat: 45.8326,
    tags: ["nature", "fitness", "travel"],
  }),
  createPost({
    id: "p006",
    authorId: "user_noah",
    author: "Noah",
    handle: "noah",
    text: "🔥 Breaking news : Manifestation importante Place de la République. Des milliers de personnes présentes. #Paris #politique",
    createdAtISO: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    kind: "normal",
    category: "news",
    signal: "strong",
    geoMode: "precise",
    status: "active",
    likes: 567,
    likedBy: ["camille", "emma", "admin"],
    comments: [
      {
        id: "c005",
        authorId: "user_camille",
        author: "Camille",
        handle: "camille",
        text: "Restez prudents ! 🙏",
        createdAtISO: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        likes: 23,
      },
    ],
    lon: 2.3633,
    lat: 48.8675,
    tags: ["politics", "news"],
  }),
  createPost({
    id: "p007",
    authorId: "user_emma",
    author: "Emma",
    handle: "emma",
    text: "Petit brunch dominical dans ce café adorable à Notting Hill ☕🥐 Ambiance parfaite pour commencer la journée #food #lifestyle",
    createdAtISO: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    kind: "normal",
    category: "vibe",
    signal: "weak",
    geoMode: "approximate",
    status: "active",
    likes: 145,
    likedBy: ["camille"],
    comments: [],
    media: {
      type: "image",
      url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
    },
    lon: -0.2058,
    lat: 51.5170,
    tags: ["food", "lifestyle"],
  }),
  createPost({
    id: "p008",
    authorId: "user_camille",
    author: "Camille",
    handle: "camille",
    text: "🎆 Feux d'artifice prévus ce soir à 22h au Château de Versailles pour la Fête Nationale ! Ne manquez pas cet événement ! #event",
    createdAtISO: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    kind: "normal",
    category: "event",
    signal: "strong",
    geoMode: "precise",
    status: "active",
    likes: 234,
    likedBy: ["noah", "emma"],
    comments: [],
    lon: 2.1204,
    lat: 48.8049,
    tags: ["events", "travel"],
  }),
  createPost({
    id: "p009",
    authorId: "user_noah",
    author: "Noah",
    handle: "noah",
    text: "⚠️ Coupure d'électricité prévue demain matin dans le 11ème arrondissement de Paris (9h-12h). Préparez-vous !",
    createdAtISO: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    kind: "normal",
    category: "alert",
    signal: "strong",
    geoMode: "precise",
    status: "active",
    likes: 78,
    likedBy: ["camille"],
    comments: [],
    lon: 2.3788,
    lat: 48.8588,
  }),
  createPost({
    id: "p010",
    authorId: "user_emma",
    author: "Emma",
    handle: "emma",
    text: "Big Ben sonne minuit ! 🎊 Bonne année à tous depuis Londres ! 2026 nous voilà ! #NewYear #London #2026",
    createdAtISO: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    kind: "normal",
    category: "event",
    signal: "strong",
    geoMode: "precise",
    status: "active",
    likes: 892,
    likedBy: ["camille", "noah", "admin"],
    comments: [
      {
        id: "c006",
        authorId: "user_camille",
        author: "Camille",
        handle: "camille",
        text: "Bonne année ! 🎉🥳",
        createdAtISO: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 60000).toISOString(),
        likes: 45,
      },
      {
        id: "c007",
        authorId: "user_noah",
        author: "Noah",
        handle: "noah",
        text: "Happy New Year! 🎆",
        createdAtISO: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 120000).toISOString(),
        likes: 38,
      },
    ],
    media: {
      type: "image",
      url: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800",
    },
    lon: -0.1246,
    lat: 51.5007,
    tags: ["events", "travel"],
  }),
  // Posts supplémentaires avec différents types de contenu
  createPost({
    id: "p011",
    authorId: "user_noah",
    author: "Noah",
    handle: "noah",
    text: "🎮 Nouvelle vidéo ! Test du dernier jeu gaming qui fait le buzz - c'est incroyable ! #gaming #tech",
    createdAtISO: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    kind: "normal",
    category: "vibe",
    signal: "weak",
    geoMode: "none",
    status: "active",
    likes: 189,
    likedBy: ["emma"],
    comments: [],
    media: {
      type: "video",
      url: "https://example.com/video.mp4",
      thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800",
    },
    tags: ["gaming", "tech"],
  }),
  createPost({
    id: "p012",
    authorId: "user_camille",
    author: "Camille",
    handle: "camille",
    text: "Nouvelle collection mode printemps 2026 ! 👗✨ Les tendances fashion sont magnifiques cette année #fashion #lifestyle",
    createdAtISO: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    kind: "normal",
    category: "vibe",
    signal: "none",
    geoMode: "none",
    status: "active",
    likes: 267,
    likedBy: ["emma", "noah"],
    comments: [],
    media: {
      type: "image",
      url: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800",
    },
    tags: ["fashion", "lifestyle"],
  }),
  createPost({
    id: "p013",
    authorId: "user_emma",
    author: "Emma",
    handle: "emma",
    text: "🔬 Découverte scientifique incroyable : des chercheurs ont fait une avancée majeure en science quantique ! #science #tech",
    createdAtISO: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    kind: "normal",
    category: "news",
    signal: "none",
    geoMode: "none",
    status: "active",
    likes: 456,
    likedBy: ["noah", "camille", "admin"],
    comments: [],
    tags: ["science", "tech"],
  }),
  createPost({
    id: "p014",
    authorId: "user_noah",
    author: "Noah",
    handle: "noah",
    text: "📷 Session photo urbaine dans les rues de Tokyo ! L'architecture est fascinante #photography #travel #art",
    createdAtISO: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    kind: "normal",
    category: "vibe",
    signal: "strong",
    geoMode: "precise",
    status: "active",
    likes: 534,
    likedBy: ["camille", "emma"],
    comments: [],
    media: {
      type: "image",
      url: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    },
    lon: 139.6917,
    lat: 35.6895,
    tags: ["photography", "travel", "art"],
  }),
];
